### ISSUE TITLE
Question: Aggregation of all queries?

### ISSUE THREAD

**Issue by Brian-McBride** [a-type/graphql-arangodb#11]
This is a very cool library you have here.

I am wondering, are you gathering up all the directives and making one single aggregated query to ArangoDB? Or does each field end up getting it's own query?

This article is a little old, but has interesting points about resolvers:
https://medium.com/paypal-engineering/graphql-resolvers-best-practices-cd36fdbcef55

The basic goal is to avoid over-fetching and using cache to optimize results. On a single document query, that's not bad. On a graph lookup, I can't see a way to cache. Well, I could if I did a graph query only getting the document ids then running queries to get that data. But, with ArangoDB, might as well just grab the documents. 

What I see is huge value in gathering all my possible queries and pulling them into one query to the server, as I am sure the DB is going to leverage internal caching where it can for speed.

**Comment by mysticaltech** [comment]
Seems very interesting, I really wish there were more developers working on this library!

**Comment by a-type** [comment]
@Brian-McBride the goal of this library is to make as few database queries as possible. By default, that's 1. 

There are sometimes good reasons to split things up into multiple queries, see [Splitting up queries](https://github.com/a-type/graphql-arangodb#splitting-up-queries-experimental) in the readme. Mostly for mutations.

You can see examples in the tests. For instance, [here's a complex GraphQL query](https://github.com/a-type/graphql-arangodb/blob/master/src/__tests__/queryTranslation.test.ts#L372) and the [output AQL query](https://github.com/a-type/graphql-arangodb/blob/master/src/__tests__/__snapshots__/queryTranslation.test.ts.snap#L4). Admittedly, the decision to use Jest Snapshots makes these hard to see. I might update them to do inline snapshots so it's easier to see how the library works.

@mysticaltech You're welcome to contribute! I know I haven't always been prompt in responding to issues here, but PRs are still welcome.

**Comment by mysticaltech** [comment]
@a-type your confidence is reassuring, thank you, I feel that we are in good hands by using your library, I will definitely contribute if one day I see something that I can improve upon (though that is unlikely as I'm a JS and GraphQL newbie). Keep up the good work!
