### ISSUE TITLE
An Idea Re: Foxx

### ISSUE THREAD

**Issue by armenr** [a-type/graphql-arangodb#9]
Dearest maintainers - 

My team and I are building some really, really cool stuff on top of Arango. We've kind of "seen the light" as far as foxx microservices are concerned, and so I'm wondering - from the perspective of the mainters of this library - how trivial/non-trivial would it be to make use of your library from within a foxx microservice?

**Comment by mysticaltech** [comment]
Hey @armenr, do you use GraphQL inside of Foxx, is it really viable and scalable option?

**Comment by danie08** [comment]
Hi @mysticaltech, also my team and I may want to use your library in Foxx microservices in ArangoDB. We are going to use GraphQL inside Foxx in a scalable solution. So our question is the same as @armenr 's one. Thank you in advance!

**Comment by mysticaltech** [comment]
@danie08 From my limited understanding of Foxx, as in runs on the DB itself, it's not really that scalable, i.e. you cannot hit it millions of times per day as you could a horizontally scalable express (Apollo or GraphQL Yoga) server. And this very project makes the need for Foxx for the specific purpose of GraphQL irrelevant. Am I missing something @a-type ?

**Comment by danie08** [comment]
@mysticaltech actually, for "scalable" I meant that we want to scale our databases. Sorry, I said it badly...

**Comment by a-type** [comment]
Wow, I'm really sorry for missing this conversation! I haven't been able to spend much time on ArangoDB projects recently, so I'm afraid this library is a tad neglected.

I remember looking into Foxx when I began working on this project but at the time it had limitations around ES6 features, and as a TypeScript developer seemed like a non-starter. I've looked at their docs to see if things have progressed, but there are still a few red flags for me.

I'm still not 100% convinced the scaling characteristics make sense. When I'm writing serverless functions or microservices running in Kubernetes, I can instantly scale up traffic by small increments based on load, and scale down later. But if my 'microservices' run on the database nodes, the scaling steps I take have to be as large as the baseline database image size. There are also other concerns about horizontal database scaling I need to take into consideration (I'd assume). It just seems like it would be a headache to do proper load-based scaling.

I'm also not a fan of the isolated nature of Foxx, which seems to make [external service requests](https://www.arangodb.com/docs/stable/foxx-guides-making-requests.html) complicated. All code being synchronous is an annoying design limitation. When I create apps, I want to leave the door open to accessing multiple unrelated services and meshing that access together with database access into one GraphQL schema.

_That said_, these are just my opinions! These opinions keep me from investing time into making this library compatible with Foxx (not to mention, I haven't worked on an Arango app in a while, so this is not high on my radar - hence the response delay). But if you would like to look into it, I'd read over a PR.

I know that's a typical open source answer, but hey, this is open source!

Reading the [resolver](https://github.com/a-type/graphql-arangodb/blob/master/src/resolver.ts) source code might be a good place to start. At a high level, it's where the various moving parts get stitched together. Basically, there's 2 steps - extract the query from GraphQL query information, and then run the query against the database. I would think to run in Foxx you'd probably need to focus on extending the second step to interface with the in-memory database access it provides. I'm sure that's no small task though.

**Comment by mysticaltech** [comment]
Makes total sense @a-type, I intuitively came up to the same conclusion.

**Comment by a-type** [comment]
I added a note about lack of Foxx support to the README, as well as a brief note on why. I'm closing this now, but if you're dead-set on adding Foxx support, the library is MIT (I just realized I forgot to add the license!) and you're welcome to fork it, gut it, do whatever you want!
